### ISSUE TITLE
прошу изменить коммит "Добавлен код Ильи"

### ISSUE THREAD

**Issue by sergey-vaytsel** [ilyapopkov/dmm-lab3-Prim-algorithm#1]
[commit link](https://github.com/ilyapopkov/dmm-lab3-Prim-algorithm/commit/ec9c1422984d5246b6029dd49a55d04330366478)

Сделайте, пожалуйста, чтобы код, относящийся к тестам, попал в мастер, а конкретная реализация Ильи.. куда нибудь в отдельную ветку, например.

Или предложите некоторый свой формат, как нам разместить все копии в одном репозитории.

Можно, например, просто добавлять все файлы в мастер, единообразно именуя.
например `prima-[bintree|vector|fibtree]-{первые_буквы_фамилий_членов_бригады}.*`
И в самом файле в комментарии писать фамилии авторов, чтобы не путаться.

После утверждения формата мы сделаем вам pull request с нашими реализациями.
В рамках pull request'а обсудим, как сделать так, чтобы это всё работало.

**Comment by mpiz** [comment]
В разных ветках держать итоговые результаты алгоритмов - глупо, тогда сравнивать их крайне не удобно.
На счёт именования. Классы и файлы, связанные с алгоритмом. Составляем из следующих частей:
1. Prim;
2. Simple/Tree/Fib;
3. _
4. первые буквы фамилий в алфавитном порядке;
Ну и да, в комментариях, в начале файла с основынм классом полный список участников команды.

**Comment by sergey-vaytsel** [comment]
Небольшой скрипт на bash или .bat файлик - и ветки больше не являются проблемой.
Но ок, пусть будет так.
